platform :ios, '9.0'

target 'Artworks' do
  use_frameworks!

  # Pods for Artworks

  target 'ArtworksTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ArtworksUITests' do
    inherit! :search_paths
    # Pods for testing
  end

    pod 'Starscream', '~> 3.0.2'
end
